# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoolestProjectCoinCollector' do
  use_frameworks!
  pod 'EstimoteSDK'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
end


